### ISSUE TITLE
EDIT: Set up static pages (OLD: Begin work on landing and variable page)

### ISSUE THREAD

**Issue by nendow02** [uclaacm/boolbots#16]
Implement code box, subtitle and robots, no functionality however (so if a user clicks a robot nothing needs to happen). The "python.tsx" file may give you an idea of how to approach this especially with using "CodeFormat.tsx". My thought here was making separate tsx files for the page and one scss for the both to share however if you have a better idea go for it!

**Comment by archishadatta** [comment]
#22
