### ISSUE TITLE
Link to Teach LA site

### ISSUE THREAD

**Issue by nendow02** [uclaacm/boolbots#18]
Add a link somewhere on the page that links back to the teach la site. Looking at [other learning labs](https://teachla.uclaacm.com/dev#projects) may give you a better idea of what the issue is asking for. Creating a design on the Figma and having someone review it first may be the best idea instead of trying to develop it right away.

**Comment by reginawang3495** [comment]
Quick thing about this ticket, on the `uclaacm/teach-la-ts-react-starter` template, we actually have a footer there already! If it fits in, we could use that footer; it might be nice for standardization of our learning labs. If there's anything that you improve on design wise, we could reflect the changes in the template as well.

Here's what it currently looks like: 
https://teach-la-ts-react-starter.netlify.app/
![image](https://user-images.githubusercontent.com/29292203/123738994-c0e7b900-d85a-11eb-9524-8374d664d3df.png)

You can yoink the code from the template.
